# @format

services:
  chrome:
    image: seleniarm/standalone-chromium:114.0
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900 #7900番ポートにアクセスするとRSpecのように自動制御されているブラウザが確認できます。
    shm_size: "2g"
    tty: true
    networks:
      - default
    environment:
      - TZ=Asia/Tokyo
      # - LANGUAGE=ja_JP.UTF-8
      # - LANG=ja_JP.UTF-8
      # - LC_ALL=ja_JP.UTF-8
  app:
    container_name: tjpw-schedule
    depends_on:
      - chrome
    build:
      context: .
      dockerfile: ./docker/src/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SELENIUM_DOMAIN=http://chrome:4444
    tty: true
    networks:
      - default
